initScope: berry

npmPublishAccess: public

plugins:
  - scripts/plugin-exec.js
  - scripts/plugin-stage.js
  - scripts/plugin-typescript.js
  - scripts/plugin-version.js
  - scripts/plugin-workspace-tools.js

yarnPath: scripts/run-yarn.js
