changesetIgnorePatterns:
  - "**/*.test.{js,ts}"
  - "packages/*/tests/**"
  - ".yarn/cache/**"

enableGlobalCache: false

pnpEnableEsmLoader: false

immutablePatterns:
  - .pnp.*

supportedArchitectures:
  os: [darwin, linux, win32]
  cpu: [x64, arm64]

initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  gatsby-cli@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      react: "*"
      webpack: "*"
  gatsby-plugin-mdx@*:
    dependencies:
      mkdirp: "*"
    peerDependencies:
      "@emotion/core": "*"
      "@emotion/react": "*"
  gatsby-recipes@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      ink: "*"
      react: "*"
      webpack: "*"
  gatsby@*:
    peerDependencies:
      "@babel/core": "*"
  monaco-editor-webpack-plugin@*:
    dependencies:
      webpack: ^4.5.0
  typedoc@*:
    peerDependenciesMeta:
      "@strictsoftware/typedoc-plugin-monorepo":
        optional: true
      typedoc-neo-theme:
        optional: true
      typedoc-plugin-yarn:
        optional: true

preferInteractive: true

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js
