initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  "@babel/parser@*":
    dependencies:
      "@babel/types": "*"
  "@emotion/babel-preset-css-prop@*":
    peerDependencies:
      "@babel/core": "*"
  "@gatsbyjs/relay-compiler@2.0.0-printer-fix.2":
    peerDependencies:
      "@babel/core": "*"
  cacheable-lookup@*:
    dependencies:
      "@types/keyv": "*"
  gatsby-plugin-emotion@*:
    peerDependencies:
      "@babel/core": "*"
  gatsby-plugin-favicon@*:
    peerDependencies:
      webpack: "*"
  gatsby@*:
    peerDependencies:
      "@babel/core": "*"
  got@*:
    dependencies:
      "@types/keyv": "*"
      "@types/responselike": "*"
  react-instantsearch-core@*:
    peerDependenciesMeta:
      algoliasearch:
        optional: true

plugins:
  - path: .yarn/plugins/plugin-local-cache.js
    spec: plugin-local-cache.js

preferDeferredVersions: true

yarnPath: scripts/run-yarn.js
