changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.test.{js,ts}"
  - packages/*/tests/**
  - packages/plugin-compat/extra/**
  - packages/docusaurus/**

compressionLevel: mixed

enableGlobalCache: false

immutablePatterns:
  - .pnp.*

initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  "@codemirror/lang-html@*":
    dependencies:
      "@codemirror/view": "*"
  "@lezer/css@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/html@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/javascript@*":
    dependencies:
      "@lezer/common": "*"
  markdown-it@*:
    dependencies:
      punycode: "*"
  react-devtools-inline@*:
    dependencies:
      react-is: "*"
      scheduler: "*"

  "@docusaurus/preset-classic@3.4.0":
    peerDependencies:
      "@docusaurus/plugin-content-docs": "*"
  docusaurus-plugin-typedoc-api@^4:
    dependencies:
      "@docusaurus/mdx-loader": "^3"
      "@docusaurus/theme-common": "^3"
    peerDependencies:
      react-dom: "*"
      typedoc: "*"
      "@docusaurus/plugin-content-docs": "*"

pnpEnableEsmLoader: true

preferInteractive: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js
