initScope: yarnpkg
npmPublishAccess: public
preferDeferredVersions: true
yarnPath: scripts/run-yarn.js

packageExtensions:
  "@emotion/babel-preset-css-prop@*":
    peerDependencies:
      "@babel/core": "*"
  "gatsby-plugin-emotion@*":
    peerDependencies:
      "@babel/core": "*"
  "gatsby@*":
    peerDependencies:
      "@babel/core": "*"
  "@gatsbyjs/relay-compiler@2.0.0-printer-fix.2":
    peerDependencies:
      "@babel/core": "*"
  "gatsby-plugin-favicon@*":
    peerDependencies:
      "webpack": "*"
  "react-instantsearch-core@*":
    peerDependenciesMeta:
      "algoliasearch":
        optional: true
