changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.test.{js,ts}"
  - packages/*/tests/**
  - packages/plugin-compat/extra/**
  - packages/docusaurus/**

compressionLevel: mixed

enableGlobalCache: false

immutablePatterns:
  - .pnp.*

initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  "@codemirror/lang-html@*":
    dependencies:
      "@codemirror/view": "*"
  "@docusaurus/core@*":
    peerDependencies:
      webpack: "*"
  "@lezer/css@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/html@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/javascript@*":
    dependencies:
      "@lezer/common": "*"
  "@docusaurus/preset-classic@2.4.3":
    peerDependencies:
      "@docusaurus/plugin-content-docs": "2.4.3"
  "@docusaurus/mdx-loader@*":
    dependencies:
      "@mdx-js/react": "^1"
  docusaurus-plugin-typedoc-api@*:
    dependencies:
      "@docusaurus/mdx-loader": "^2"
      "@docusaurus/theme-common": "^2"
    peerDependencies:
      react-dom: ">=16.0.0"
      typedoc: "^0.25.0"
      "@docusaurus/plugin-content-docs": "*"
  markdown-it@*:
    dependencies:
      punycode: "*"
  react-devtools-inline@*:
    dependencies:
      react-is: "*"
      scheduler: "*"

pnpEnableEsmLoader: true

preferInteractive: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js
