## General settings

initScope:
  berry

npmPublishAccess:
  public

yarnPath:
  scripts/run-yarn.js

## List of plugins enabled in the current repository

plugins:
  - scripts/plugin-exec.js
  - scripts/plugin-stage.js
  - scripts/plugin-typescript.js
  - scripts/plugin-version.js
  - scripts/plugin-workspace-tools.js
