changesetIgnorePatterns:
  - "**/*.test.{js,ts}"

enableGlobalCache: false

initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  "@babel/parser@*":
    dependencies:
      "@babel/types": "*"
  "@emotion/babel-preset-css-prop@*":
    peerDependencies:
      "@babel/core": "*"
  "@gatsbyjs/relay-compiler@2.0.0-printer-fix.2":
    peerDependencies:
      "@babel/core": "*"
  cacheable-lookup@*:
    dependencies:
      "@types/keyv": "*"
  gatsby-cli@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      react: "*"
      webpack: "*"
  gatsby-plugin-emotion@*:
    peerDependencies:
      "@babel/core": "*"
  gatsby-plugin-favicon@*:
    peerDependencies:
      webpack: "*"
  gatsby-plugin-sharp@*:
    dependencies:
      debug: "*"
  gatsby-react-router-scroll@*:
    dependencies:
      prop-types: "*"
  gatsby-recipes@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      ink: "*"
      react: "*"
      webpack: "*"
  gatsby-remark-prismjs@*:
    dependencies:
      lodash: "*"
  gatsby@*:
    peerDependencies:
      "@babel/core": "*"
    peerDependenciesMeta:
      "@types/react":
        optional: true
  got@*:
    dependencies:
      "@types/keyv": "*"
      "@types/responselike": "*"
  json-ref-lite@*:
    dependencies:
      sync-request: "*"
  rc-animate@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  react-icons@*:
    peerDependencies:
      react: "*"
  react-instantsearch-core@*:
    peerDependenciesMeta:
      algoliasearch:
        optional: true
  typedoc@*:
    peerDependenciesMeta:
      "@strictsoftware/typedoc-plugin-monorepo":
        optional: true
      typedoc-neo-theme:
        optional: true
      typedoc-plugin-yarn:
        optional: true

yarnPath: scripts/run-yarn.js
