changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.test.{js,ts}"
  - packages/*/tests/**
  - packages/plugin-compat/extra/**
  - packages/docusaurus/**

compressionLevel: mixed

enableGlobalCache: false

immutablePatterns:
  - .pnp.*

initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  "@codemirror/lang-html@*":
    dependencies:
      "@codemirror/view": "*"
  "@docusaurus/core@*":
    peerDependencies:
      webpack: "*"
  "@lezer/css@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/html@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/javascript@*":
    dependencies:
      "@lezer/common": "*"
  markdown-it@*:
    dependencies:
      punycode: "*"
  react-devtools-inline@*:
    dependencies:
      react-is: "*"
      scheduler: "*"

pnpEnableEsmLoader: true

preferInteractive: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js
