changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.test.{js,ts}"
  - packages/*/tests/**
  - packages/plugin-compat/extra/**
  - packages/gatsby/**

compressionLevel: mixed

enableGlobalCache: false

immutablePatterns:
  - .pnp.*

initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  "@codemirror/lang-html@*":
    dependencies:
      "@codemirror/view": "*"
  "@lezer/css@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/html@*":
    dependencies:
      "@lezer/common": "*"
  "@lezer/javascript@*":
    dependencies:
      "@lezer/common": "*"
  gatsby-cli@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      react: "*"
      webpack: "*"
  gatsby-plugin-mdx@*:
    peerDependencies:
      "@emotion/core": "*"
      "@emotion/react": "*"
  gatsby-recipes@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      ink: "*"
      react: "*"
      webpack: "*"
  gatsby@*:
    peerDependencies:
      "@babel/core": "*"
  markdown-it@*:
    dependencies:
      punycode: "*"
  monaco-editor-webpack-plugin@*:
    dependencies:
      webpack: ^4.5.0
  react-devtools-inline@*:
    dependencies:
      react-is: "*"
      scheduler: "*"
  typedoc@*:
    peerDependenciesMeta:
      "@strictsoftware/typedoc-plugin-monorepo":
        optional: true
      typedoc-neo-theme:
        optional: true
      typedoc-plugin-yarn:
        optional: true

pnpEnableEsmLoader: true

preferInteractive: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js
