#changesetIgnorePatterns:
#  - "**/*.test.{js,ts}"

enableGlobalCache: false

immutablePatterns:
  - .pnp.*

initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  "@webpack-cli/package-utils@*":
    dependencies:
      cross-spawn: "*"
  gatsby-cli@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      react: "*"
      webpack: "*"
  gatsby-plugin-favicon@*:
    peerDependencies:
      webpack: "*"
  gatsby-plugin-sharp@*:
    dependencies:
      debug: "*"
  gatsby-react-router-scroll@*:
    dependencies:
      prop-types: "*"
  gatsby-recipes@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      ink: "*"
      react: "*"
      webpack: "*"
  gatsby-remark-prismjs@*:
    dependencies:
      lodash: "*"
  gatsby@*:
    peerDependencies:
      "@babel/core": "*"
  monaco-editor-webpack-plugin@*:
    dependencies:
      webpack: ^4.5.0
  typedoc@*:
    peerDependenciesMeta:
      "@strictsoftware/typedoc-plugin-monorepo":
        optional: true
      typedoc-neo-theme:
        optional: true
      typedoc-plugin-yarn:
        optional: true

preferInteractive: true

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js
