catalog:
  typescript: ^5.9.2

changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.test.{js,ts}"
  - packages/*/tests/**
  - packages/plugin-compat/extra/**
  - packages/docusaurus/**

compressionLevel: mixed

enableGlobalCache: false

immutablePatterns:
  - .pnp.*

initScope: yarnpkg

npmMinimalAgeGate: 0

npmPublishAccess: public

npmPublishProvenance: true

packageExtensions:
  "@docusaurus/preset-classic@3.7.0":
    peerDependencies:
      "@docusaurus/plugin-content-docs": 3.7.0
  docusaurus-plugin-typedoc-api@^4:
    dependencies:
      "@docusaurus/mdx-loader": ^3
      "@docusaurus/theme-common": ^3
    peerDependencies:
      "@docusaurus/plugin-content-docs": "*"
      react-dom: "*"
      typedoc: "*"
  markdown-it@*:
    dependencies:
      punycode: "*"

pnpEnableEsmLoader: true

pnpZipBackend: js

preferInteractive: true

supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - darwin
    - linux
    - win32

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js
