changesetIgnorePatterns:
  - "**/*.test.{js,ts}"

enableGlobalCache: false

immutablePatterns:
  - .pnp.*

initScope: yarnpkg

npmPublishAccess: public

packageExtensions:
  "@babel/parser@*":
    dependencies:
      "@babel/types": "*"
  "@emotion/babel-preset-css-prop@*":
    peerDependencies:
      "@babel/core": "*"
  "@gatsbyjs/relay-compiler@2.0.0-printer-fix.2":
    peerDependencies:
      "@babel/core": "*"
  "@webpack-cli/package-utils@*":
    dependencies:
      cross-spawn: "*"
  fork-ts-checker-webpack-plugin@*:
    peerDependencies:
      typescript: "*"
  gatsby-cli@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      react: "*"
      webpack: "*"
  gatsby-plugin-emotion@*:
    peerDependencies:
      "@babel/core": "*"
  gatsby-plugin-favicon@*:
    peerDependencies:
      webpack: "*"
  gatsby-plugin-sharp@*:
    dependencies:
      debug: "*"
  gatsby-react-router-scroll@*:
    dependencies:
      prop-types: "*"
  gatsby-recipes@*:
    peerDependencies:
      eslint: "*"
      gatsby: "*"
      ink: "*"
      react: "*"
      webpack: "*"
  gatsby-remark-prismjs@*:
    dependencies:
      lodash: "*"
  gatsby@*:
    peerDependencies:
      "@babel/core": "*"
    peerDependenciesMeta:
      "@types/react":
        optional: true
  json-ref-lite@*:
    dependencies:
      sync-request: "*"
  monaco-editor-webpack-plugin@*:
    dependencies:
      webpack: ^4.5.0
  rc-animate@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  react-icons@*:
    peerDependencies:
      react: "*"
  react-instantsearch-core@*:
    peerDependenciesMeta:
      algoliasearch:
        optional: true
  react-instantsearch-dom@*:
    dependencies:
      react-fast-compare: "*"
  typedoc@*:
    peerDependenciesMeta:
      "@strictsoftware/typedoc-plugin-monorepo":
        optional: true
      typedoc-neo-theme:
        optional: true
      typedoc-plugin-yarn:
        optional: true

preferInteractive: true

telemetryUserId: yarnpkg/berry

yarnPath: scripts/run-yarn.js
