initScope: yarnpkg

npmPublishAccess: public

preferDeferredVersions: true

plugins:
  - scripts/plugin-exec.js
  - scripts/plugin-stage.js
  - scripts/plugin-typescript.js
  - scripts/plugin-workspace-tools.js

yarnPath: scripts/run-yarn.js
