initScope: yarnpkg
npmPublishAccess: public
preferDeferredVersions: true
enableGlobalCache: false
yarnPath: scripts/run-yarn.js

packageExtensions:
  "@babel/parser@*":
    dependencies:
      "@babel/types": "*"
  "@emotion/babel-preset-css-prop@*":
    peerDependencies:
      "@babel/core": "*"
  "gatsby-plugin-emotion@*":
    peerDependencies:
      "@babel/core": "*"
  "gatsby@*":
    peerDependencies:
      "@babel/core": "*"
  "@gatsbyjs/relay-compiler@2.0.0-printer-fix.2":
    peerDependencies:
      "@babel/core": "*"
  "cacheable-lookup@*":
    dependencies:
      "@types/keyv": "*"
  "gatsby-plugin-favicon@*":
    peerDependencies:
      "webpack": "*"
  "got@*":
    dependencies:
      "@types/keyv": "*"
      "@types/responselike": "*"
  "react-instantsearch-core@*":
    peerDependenciesMeta:
      "algoliasearch":
        optional: true
  "json-ref-lite@*":
    dependencies:
      "sync-request": "*"
