runs:
  using: composite
  steps:
    - uses: actions/setup-node@master
      with:
        node-version: 16.x
        check-latest: true

    #region Build the standard bundle
    - uses: actions/cache@v2
      id: cache-build
      with:
        path: packages/yarnpkg-cli/bundles/yarn.js
        key: cli-bundle-${{ github.sha }}

    - name: 'Build the standard bundle'
      if: steps.cache-build.outputs.cache-hit != 'true'
      run: |
        node ./scripts/run-yarn.js build:cli
      shell: bash
    #endregion

    #region Cache workflow dependencies
    - name: Get global path
      id: global-path
      run: echo "::set-output name=globalFolder::$(YARN_IGNORE_PATH=1 node packages/yarnpkg-cli/bundles/yarn.js config get globalFolder)"
      shell: bash

    - uses: actions/cache@v2
      with:
        path: ${{ steps.global-path.outputs.globalFolder }}/cache
        key: dependencies-${{ runner.os }}-${{ github.workflow }}-${{ github.sha }}
    #endregion
