[package]
name = "yarnpkg-parsers"
version = "0.0.0"
license = "BSD-2-Clause"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
nom = "7.1.1"
nom-supreme = "0.8.0"
cow-utils = "0.1.2"
rustc-hash = "1.1.0"
indexmap = { version = "1.9.2", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91", features = ["preserve_order"] }
wasm-bindgen = "0.2.83"

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O4"]
