on:
  push:
    branches:
    - master
    paths:
    - .github/workflows/doc-workflow.yml
    - packages/*/sources/commands/**/*.ts
    - packages/gatsby/**/*

name: 'Documentation'
jobs:
  documentation:
    name: 'Building the documentation'
    runs-on: ubuntu-latest

    steps:
    - name: 'Check user'
      uses: actions/bin/filter@master
      with:
        args: 'not actor yarnbot'

    - uses: actions/checkout@master

    - name: 'Use Node.js 10.x'
      uses: actions/setup-node@master
      with:
        version: 10.x

    - name: 'Run Yarn install (for binary deps)'
      run: |
        node ./scripts/run-yarn.js install --inline-builds

    - name: 'Build the documentation'
      run: |
        node ./scripts/run-yarn.js build:doc

    - name: 'Check whether a new deploy is needed'
      run: |
        [[ -n $(git status --short) ]] || exit 78

    - name: 'Make the commit'
      uses: ./scripts/actions/make-commit
      with:
        message: 'Updates the documentation website'
      env:
        GITHUB_TOKEN: ${{secrets.YARNBOT_TOKEN}}

#
