on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-preact-cli-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Preact CLI'
jobs:
  chore:
    name: 'Validating Preact CLI'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: ./.github/actions/prepare
      with:
        # Remove when Preact CLI supports Node.js 18
        node-version: 16.x

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        yarn dlx preact-cli create default default-app --yarn
        cd default-app
        yarn build

    - name: 'Running the TypeScript integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        yarn dlx preact-cli create typescript ts-app --yarn
        cd ts-app
        yarn build
      if: |
        success() || failure()
