# test

on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/actions/prepare/action.yml
    - .github/workflows/e2e-pnpify-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Angular over PnPify'
jobs:
  chore:
    name: 'Validating Angular over PnPify'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: ./.github/actions/prepare

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        yarn dlx -p @angular/cli@next ng new berry-angular --interactive=false

        cd berry-angular

        yarn add @yarnpkg/pnpify @angular-devkit/core@next @babel/preset-env @babel/core -D

        yarn unplug -AR @angular/platform-browser @angular/core @angular/common @angular/compiler-cli

        yarn pnpify ng build --aot
