on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/e2e-eslint-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E TypeScript ESLint'
jobs:
  chore:
    name: 'Validating TypeScript ESLint'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Use Node.js 10.x'
      uses: actions/setup-node@master
      with:
        node-version: 10.x

    - name: 'Build the standard bundle'
      run: |
        node ./scripts/run-yarn.js build:cli

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh

        yarn init -p
        yarn add eslint typescript @typescript-eslint/parser @typescript-eslint/eslint-plugin

        echo '{"rules": {"@typescript-eslint/explicit-function-return-type": "error"}, "extends": ["plugin:@typescript-eslint/recommended"]}' > .eslintrc

        echo 'const f = (): number => 42;' | tee ok.ts
        yarn eslint ok.ts

        echo 'const f = () => 42;' | tee ko.ts
        ! yarn eslint ko.ts
