on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/e2e-preact-cli-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Preact CLI'
jobs:
  chore:
    name: 'Validating Preact CLI'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Install Node'
      uses: actions/setup-node@master
      with:
        node-version: 14.x

    - name: 'Build the standard bundle'
      run: |
        node ./scripts/run-yarn.js build:cli

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        git clone https://github.com/preactjs-templates/default.git default
        cd default/template
        touch yarn.lock
        echo $(cat package.json | jq '.name = "pnp-test"') > package.json
        yarn
        yarn build

    - name: 'Running the TypeScript integration test'
      run: |
        source scripts/e2e-setup-ci.sh
        git clone https://github.com/preactjs-templates/typescript.git default
        cd default/template
        touch yarn.lock
        echo $(cat package.json | jq '.name = "pnp-test"') > package.json
        yarn
        yarn build
