on:
  schedule:
  - cron: '0 */4 * * *'
  push:
    branches:
    - master
  pull_request:
    paths:
    - .github/workflows/e2e-angular-workflow.yml
    - scripts/e2e-setup-ci.sh

name: 'E2E Angular'
jobs:
  chore:
    name: 'Validating Angular'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: 'Use Node.js 10.x'
      uses: actions/setup-node@master
      with:
        version: 10.x

    - name: 'Build the standard bundle'
      run: |
        node ./scripts/run-yarn.js build:cli

    - name: 'Running the integration test'
      run: |
        source scripts/e2e-setup-ci.sh;

        yarn dlx -p @angular/cli@next ng new berry-angular --interactive=false

        cd berry-angular
        echo 'nodeLinker: node-modules' >> .yarnrc.yml

        yarn add @angular-devkit/core@next @babel/preset-env @babel/core -D

        yarn ng build --aot
