# Handles packaging Yarn into Debian and RPM packages
on:
  push:
    branches:
    - master
    paths:
    - scripts/actions/build-deb
    - .github/workflows/package-workflow.yml
  pull_request:
    paths:
    - scripts/actions/build-deb
    - .github/workflows/package-workflow.yml

name: 'Release Packages'
jobs:
  linux-packages:
    name: 'Linux Packages'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@master
      with:
        node-version: 12.x

    - name: 'Build the standard bundle'
      run: |
        set -ex
        node ./scripts/run-yarn.js build:cli

    - name: 'Build the dist directory'
      run: |
        ./scripts/build-dist.sh

    - name: 'Build the deb archive'
      uses: ./scripts/actions/build-deb
