on:
  workflow_run:
    workflows: ['Smart merge: Generate']
    types:
      - completed

name: 'Smart merge: Apply'
jobs:
  apply:
    name: 'Apply the update changeset'
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{github.event.workflow_run.head_sha}}

      - name: 'Download the artifacts'
        uses: actions/github-script@v3
        with:
          script: |
            const fs = require(`fs`);

            const artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: ${{github.event.workflow_run.id}},
            });

            const matchArtifact = artifacts.data.artifacts.filter(artifact => {
              return artifact.name == `pr`;
            })[0];

            const download = await github.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: `zip`,
            });

            fs.writeFileSync(`${{github.workspace}}/pr.zip`, Buffer.from(download.data));

      - name: Unpack the artifacts
        run: unzip pr.zip

      - name: Apply the changeset
        run: |
          PR_META=$(curl https://api.github.com/repos/yarnpkg/berry/pulls/'${{github.event.inputs.pr}}')

          PR_REPO=$(jq -r .head.repo.full_name <<< "$PR_META")
          PR_REF=$(jq -r .head.ref <<< "$PR_META")

          git config user.name "Yarn Bot"
          git config user.email nison.mael+yarnbot@gmail.com

          git remote add pr-source https://'${{secrets.YARNBOT_TOKEN}}'@github.com/"$PR_REPO".git

          git fetch --depth=1 pr-source "$PR_REF":local
          git checkout local

          git merge --no-commit origin/master || true
          git apply pr/update.patch
          git commit -m 'Auto-merge with master'

          git push pr-source local:"$PR_REF"
