on:
  pull_request_target:
    types: [labeled]

name: 'Smart merge: Reset'
jobs:
  generate:
    name: 'Remove the label'
    runs-on: ubuntu-latest
    if: |
      github.event.label.name == 'infra: pending update'

    steps:
      - name: 'Remove the label'
        uses: actions/github-script@v3
        with:
          script: |
            await github.rest.issues.removeLabel({
               owner: context.repo.owner,
               repo: context.repo.repo,
               issue_number: context.pull_request.number,
               name: `infra: pending update`,
            });
