on:
  workflow_dispatch:
    inputs:
      commit_sha:
        description: 'Commit SHA to release from'
        required: true
        type: string
      release_script_ref:
        description: 'If set, copy scripts/release from this ref before running'
        required: false
        type: string

env:
  node-version: '18.x'

name: 'Re-release'
jobs:
  release:
    name: 'Re-releasing artifacts'
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --max_old_space_size=8192

    # Mint a token to produce the provenance statement
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.event.inputs.commit_sha}}
        token: ${{secrets.YARNBOT_TOKEN}}

    - name: 'Retrieve all the relevant tags'
      run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

    - name: 'Use Node.js ${{ env.node-version }}'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node-version }}

    - name: 'Build a binary for convenience'
      run: |
        yarn build:cli --no-git-hash

        TMPBIN=$(mktemp -d)
        cp ./packages/yarnpkg-cli/bundles/yarn.js $TMPBIN/yarn.js

        grep -v "yarnPath:" .yarnrc.yml > $TMPBIN/.yarnrc.yml
        cp $TMPBIN/.yarnrc.yml .yarnrc.yml
        echo "yarnPath: '$TMPBIN/yarn.js'" >> .yarnrc.yml
        git update-index --skip-worktree -- .yarnrc.yml

    - name: 'Override release scripts'
      if: ${{github.event.inputs.release_script_ref}}
      run: |
        git fetch origin ${{github.event.inputs.release_script_ref}} --depth=1
        git checkout ${{github.event.inputs.release_script_ref}} -- scripts/release

        git config user.name "Yarn Bot"
        git config user.email nison.mael+yarnbot@gmail.com

        git add .
        git commit -m 'Temporary commit for a pristine repository'

    - name: 'Upload the releases'
      run: |
        yarn config set -H 'npmAuthToken' "${{secrets.YARNBOT_NPM_TOKEN}}"
        yarn config set -H 'npmRegistries["//npm.pkg.github.com"].npmAuthToken' "${{secrets.YARNBOT_TOKEN}}"
        ./scripts/release/02-release-builds.sh
        ./scripts/release/03-release-npm.sh
